PROJECT_NAME=PartsUnlimitedMRP
#PROJECT_NAME=JPetstore
#PROJECT_NAME=everest

STATIC=../dependencyGraphs/static/${PROJECT_NAME}StaticGraph.csv
DYNAMIC=../dependencyGraphs/dynamic/fosci/${PROJECT_NAME}DynamicFosciGraph.csv
CLASSTERMS=../dependencyGraphs/semantic/classTerms/${PROJECT_NAME}ClassTermsGraph.csv
CLASSNAMES=../dependencyGraphs/semantic/className/${PROJECT_NAME}ClassNameGraph.csv
CONTRIBUTOR=../dependencyGraphs/evolutionary/contributors/${PROJECT_NAME}ContributorGraph.csv
COMMIT=../dependencyGraphs/evolutionary/commits/${PROJECT_NAME}CommitGraph.csv

IS_DIRECTED=0
MIN_EDGE_WEIGHT=1
BUNCH_OUTPUT=./bunch
mkdir weightedGraphs
mkdir weightedGraphs/${PROJECT_NAME}

#STATIC_WEIGHT=0.5
#DYNAMIC_WEIGHT=0.5
#CLASSNAMES_WEIGHT=0.0
#CLASSTERMS_WEIGHT=0.0
#COMMIT_WEIGHT=0.0
#CONTRIBUTOR_WEIGHT=0.0
#BUNCH_OUTPUT=./bunch/${PROJECT_NAME}/
#mkdir ${BUNCH_OUTPUT}
#DEPENDENCY=structural
#GRAPH_OUTPUT=./weightedGraphs/${PROJECT_NAME}/${DEPENDENCY}
#python3 generateWeightedGraph.py ${GRAPH_OUTPUT}.csv ${STATIC} ${DYNAMIC} ${CLASSNAMES} ${CLASSTERMS} ${CONTRIBUTOR} ${COMMIT} ${STATIC_WEIGHT} ${DYNAMIC_WEIGHT} ${CLASSNAMES_WEIGHT} ${CLASSTERMS_WEIGHT} ${CONTRIBUTOR_WEIGHT} ${COMMIT_WEIGHT} 
#python3 ../fileFormatConversionScripts/extractMDGfromCSV.py ${GRAPH_OUTPUT}.csv #outputs .mdg file...
#javac RunBunch.java
#java RunBunch ${GRAPH_OUTPUT}.mdg ${BUNCH_OUTPUT}
#python3 ../fileFormatConversionScripts/extractRSFfromBunch.py ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.bunch
##dot -Tpdf ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.dot -o ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.pdf

STATIC_WEIGHT=1.0
DYNAMIC_WEIGHT=0.0
CLASSNAMES_WEIGHT=0.0
CLASSTERMS_WEIGHT=0.0
COMMIT_WEIGHT=0.0
CONTRIBUTOR_WEIGHT=0.0
DEPENDENCY=static
GRAPH_OUTPUT=../
GRAPH_OUTPUT=../../wem-web/public/dependencyGraphs/${PROJECT_NAME}/${DEPENDENCY}
python3 generateWeightedGraph.py ${GRAPH_OUTPUT}.csv ${STATIC} ${DYNAMIC} ${CLASSNAMES} ${CLASSTERMS} ${CONTRIBUTOR} ${COMMIT} ${STATIC_WEIGHT} ${DYNAMIC_WEIGHT} ${CLASSNAMES_WEIGHT} ${CLASSTERMS_WEIGHT} ${CONTRIBUTOR_WEIGHT} ${COMMIT_WEIGHT} 
STATIC_WEIGHT=0.0
DYNAMIC_WEIGHT=1.0
CLASSNAMES_WEIGHT=0.0
CLASSTERMS_WEIGHT=0.0
COMMIT_WEIGHT=0.0
CONTRIBUTOR_WEIGHT=0.0
DEPENDENCY=dynamic
GRAPH_OUTPUT=../../wem-web/public/dependencyGraphs/${PROJECT_NAME}/${DEPENDENCY}
python3 generateWeightedGraph.py ${GRAPH_OUTPUT}.csv ${STATIC} ${DYNAMIC} ${CLASSNAMES} ${CLASSTERMS} ${CONTRIBUTOR} ${COMMIT} ${STATIC_WEIGHT} ${DYNAMIC_WEIGHT} ${CLASSNAMES_WEIGHT} ${CLASSTERMS_WEIGHT} ${CONTRIBUTOR_WEIGHT} ${COMMIT_WEIGHT} 
STATIC_WEIGHT=0.0
DYNAMIC_WEIGHT=0.0
CLASSNAMES_WEIGHT=1.0
CLASSTERMS_WEIGHT=0.0
COMMIT_WEIGHT=0.0
CONTRIBUTOR_WEIGHT=0.0
DEPENDENCY=classnames
GRAPH_OUTPUT=../../wem-web/public/dependencyGraphs/${PROJECT_NAME}/${DEPENDENCY}
python3 generateWeightedGraph.py ${GRAPH_OUTPUT}.csv ${STATIC} ${DYNAMIC} ${CLASSNAMES} ${CLASSTERMS} ${CONTRIBUTOR} ${COMMIT} ${STATIC_WEIGHT} ${DYNAMIC_WEIGHT} ${CLASSNAMES_WEIGHT} ${CLASSTERMS_WEIGHT} ${CONTRIBUTOR_WEIGHT} ${COMMIT_WEIGHT} 
STATIC_WEIGHT=0.0
DYNAMIC_WEIGHT=0.0
CLASSNAMES_WEIGHT=0.0
CLASSTERMS_WEIGHT=1.0
COMMIT_WEIGHT=0.0
CONTRIBUTOR_WEIGHT=0.0
DEPENDENCY=classterms
GRAPH_OUTPUT=../../wem-web/public/dependencyGraphs/${PROJECT_NAME}/${DEPENDENCY}
python3 generateWeightedGraph.py ${GRAPH_OUTPUT}.csv ${STATIC} ${DYNAMIC} ${CLASSNAMES} ${CLASSTERMS} ${CONTRIBUTOR} ${COMMIT} ${STATIC_WEIGHT} ${DYNAMIC_WEIGHT} ${CLASSNAMES_WEIGHT} ${CLASSTERMS_WEIGHT} ${CONTRIBUTOR_WEIGHT} ${COMMIT_WEIGHT} 
STATIC_WEIGHT=0.0
DYNAMIC_WEIGHT=0.0
CLASSNAMES_WEIGHT=0.0
CLASSTERMS_WEIGHT=0.0
COMMIT_WEIGHT=1.0
CONTRIBUTOR_WEIGHT=0.0
DEPENDENCY=commit
GRAPH_OUTPUT=../../wem-web/public/dependencyGraphs/${PROJECT_NAME}/${DEPENDENCY}
python3 generateWeightedGraph.py ${GRAPH_OUTPUT}.csv ${STATIC} ${DYNAMIC} ${CLASSNAMES} ${CLASSTERMS} ${CONTRIBUTOR} ${COMMIT} ${STATIC_WEIGHT} ${DYNAMIC_WEIGHT} ${CLASSNAMES_WEIGHT} ${CLASSTERMS_WEIGHT} ${CONTRIBUTOR_WEIGHT} ${COMMIT_WEIGHT} 
STATIC_WEIGHT=0.0
DYNAMIC_WEIGHT=0.0
CLASSNAMES_WEIGHT=0.0
CLASSTERMS_WEIGHT=0.0
COMMIT_WEIGHT=0.0
CONTRIBUTOR_WEIGHT=1.0
DEPENDENCY=contributor
GRAPH_OUTPUT=../../wem-web/public/dependencyGraphs/${PROJECT_NAME}/${DEPENDENCY}
python3 generateWeightedGraph.py ${GRAPH_OUTPUT}.csv ${STATIC} ${DYNAMIC} ${CLASSNAMES} ${CLASSTERMS} ${CONTRIBUTOR} ${COMMIT} ${STATIC_WEIGHT} ${DYNAMIC_WEIGHT} ${CLASSNAMES_WEIGHT} ${CLASSTERMS_WEIGHT} ${CONTRIBUTOR_WEIGHT} ${COMMIT_WEIGHT} 
#python3 ../fileFormatConversionScripts/extractMDGfromCSV.py ${GRAPH_OUTPUT}.csv #outputs .mdg file...
#java RunBunch ${GRAPH_OUTPUT}.mdg ${BUNCH_OUTPUT}
#python3 ../fileFormatConversionScripts/extractRSFfromBunch.py ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.bunch
#dot -Tpdf ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.dot -o ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.pdf

#STATIC_WEIGHT=0
#DYNAMIC_WEIGHT=0
#CLASSNAMES_WEIGHT=0
#CLASSTERMS_WEIGHT=0
#COMMIT_WEIGHT=0.5
#CONTRIBUTOR_WEIGHT=0.5
#DEPENDENCY=evolutionary
#GRAPH_OUTPUT=./weightedGraphs/${PROJECT_NAME}/${DEPENDENCY}
#python3 generateWeightedGraph.py ${GRAPH_OUTPUT}.csv ${STATIC} ${DYNAMIC} ${CLASSNAMES} ${CLASSTERMS} ${CONTRIBUTOR} ${COMMIT} ${STATIC_WEIGHT} ${DYNAMIC_WEIGHT} ${CLASSNAMES_WEIGHT} ${CLASSTERMS_WEIGHT} ${CONTRIBUTOR_WEIGHT} ${COMMIT_WEIGHT} 
#python3 ../fileFormatConversionScripts/extractMDGfromCSV.py ${GRAPH_OUTPUT}.csv #outputs .mdg file...
#java RunBunch ${GRAPH_OUTPUT}.mdg ${BUNCH_OUTPUT}
#python3 ../fileFormatConversionScripts/extractRSFfromBunch.py ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.bunch
##dot -Tpdf ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.dot -o ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.pdf
#
#STATIC_WEIGHT=1
#DYNAMIC_WEIGHT=1
#CLASSNAMES_WEIGHT=1
#CLASSTERMS_WEIGHT=1
#COMMIT_WEIGHT=1
#CONTRIBUTOR_WEIGHT=1
#DEPENDENCY=all-unweighted
#GRAPH_OUTPUT=./weightedGraphs/${PROJECT_NAME}/${DEPENDENCY}
#python3 generateWeightedGraph.py ${GRAPH_OUTPUT}.csv ${STATIC} ${DYNAMIC} ${CLASSNAMES} ${CLASSTERMS} ${CONTRIBUTOR} ${COMMIT} ${STATIC_WEIGHT} ${DYNAMIC_WEIGHT} ${CLASSNAMES_WEIGHT} ${CLASSTERMS_WEIGHT} ${CONTRIBUTOR_WEIGHT} ${COMMIT_WEIGHT} 
#python3 ../fileFormatConversionScripts/extractMDGfromCSV.py ${GRAPH_OUTPUT}.csv #outputs .mdg file...
#java RunBunch ${GRAPH_OUTPUT}.mdg ${BUNCH_OUTPUT}
#python3 ../fileFormatConversionScripts/extractRSFfromBunch.py ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.bunch
##dot -Tpdf ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.dot -o ${BUNCH_OUTPUT}/${DEPENDENCY}.mdg.pdf
